name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, pdo, bcmath, json, tokenizer, xml

      - name: Install Composer Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Install sshpass
        run: sudo apt-get install sshpass  # Install sshpass on the runner

      - name: Enable Maintenance Mode on Server 1
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USERNAME }}
          password: ${{ secrets.SERVER1_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/test-action
            # Add debugging info
            echo "Current PATH: $PATH"
            php -v
            php artisan down
        env:
          SSH_AUTH_SOCK: /dev/null

      - name: Deploy Code on Server 2
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.SERVER2_USERNAME }}
          password: ${{ secrets.SERVER2_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/test-action
            # Add debugging info
            echo "Current PATH: $PATH"
            # php -v
            # sh deploy.sh # Execute the deploy.sh script
        env:
          SSH_AUTH_SOCK: /dev/null

      - name: Disable Maintenance Mode on Server 1 and Run Deploy Script
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USERNAME }}
          password: ${{ secrets.SERVER1_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/test-action
            # Add debugging info
            echo "Current PATH: $PATH"
            php -v
            php artisan up
            # sh deploy.sh # Execute the deploy.sh script
        env:
          SSH_AUTH_SOCK: /dev/null
