---
  name: Laravel Deployment
  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Enable Maintenance Mode on Server 1
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER1_HOST }}
            username: ${{ secrets.SERVER1_USERNAME }}
            key: ${{ secrets.SSH_PUBLIC_KEY_SERVER1 }}
            port: 22
            script: |
              cd /var/www/html/test-action
              php artisan down
          env:
            SSH_AUTH_SOCK: /dev/null
        - name: Deploy Code on Server 2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER2_HOST }}
            username: ${{ secrets.SERVER2_USERNAME }}
            key: ${{ secrets.SSH_PUBLIC_KEY_SERVER2 }}
            port: 22
            script: |
              cd /var/www/html/test-action
              sh deploy.sh # Execute the deploy.sh script
          env:
            SSH_AUTH_SOCK: /dev/null
        - name: Disable Maintenance Mode on Server 1 and Run Deploy Script
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER1_HOST }}
            username: ${{ secrets.SERVER1_USERNAME }}
            key: ${{ secrets.SSH_PUBLIC_KEY_SERVER1 }}
            port: 22
            script: |
              cd /var/www/html/test-action
              php artisan up
              sh deploy.sh # Execute the deploy.sh script
          env:
            SSH_AUTH_SOCK: /dev/null
  