name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  configure_php:
    runs-on: ubuntu-latest
    steps:
      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, pdo, bcmath, json, tokenizer, xml

  install_composer_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Composer Dependencies
        working-directory: /var/www/html/test-action
        run: composer install --no-dev --no-interaction --prefer-dist

  install_sshpass:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install sshpass  # Install sshpass on the runner

  enable_maintenance_mode:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Maintenance Mode on Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USERNAME }}
          password: ${{ secrets.SERVER1_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/test-action
            # Add debugging info
            echo "Current PATH: $PATH"
            php -v
            php artisan down
        env:
          SSH_AUTH_SOCK: /dev/null

  deploy_code_server2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code on Server 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.SERVER2_USERNAME }}
          password: ${{ secrets.SERVER2_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/test-action
            # Add debugging info
            echo "Current PATH: $PATH"
            # php -v
            # sh deploy.sh # Execute the deploy.sh script
        env:
          SSH_AUTH_SOCK: /dev/null

  disable_maintenance_mode:
    runs-on: ubuntu-latest
    steps:
      - name: Disable Maintenance Mode on Server 1 and Run Deploy Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USERNAME }}
          password: ${{ secrets.SERVER1_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/test-action
            # Add debugging info
            echo "Current PATH: $PATH"
            php -v
            php artisan up
            # sh deploy.sh # Execute the deploy.sh script
        env:
          SSH_AUTH_SOCK: /dev/null
